Small fixes to spanish translation
AnthonyMonette/TheWitcherTRPG pull request #80
Opened 2021-08-16 00:40 UTC by lozalojo

2021-08-16 01:08 UTC, AnthonyMonette commented on lang/es.json
> +    "WITCHER.Weapon.0": "CD.",
This must stays Concealement

2021-08-16 01:09 UTC, AnthonyMonette requested changes
The Localization has been completed for the system. But there is a lot of localization missing for Spanish.  It would be nice if you could complete it ! thanks

2021-08-16 08:13 UTC, lozalojo commented
Sorry, I am not the one translating, just helping a friend which does not know git, just validated the es.json file and sent the PR, I will ask him to complete the translation, check it and send the PR again, but looks like there are a lot of keys missing, it will take some time.

2021-08-17 13:35 UTC, lozalojo commented
@AnthonyMonette , included all keys in the translation file es.json, its ready now

2021-08-19 05:38 UTC, merged